/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uhv1.Vistas;

import uhv1.ControlPrincipal;

/**
 *
 * @author darky
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ControlPrincipal control;
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal(ControlPrincipal control) {
        this.control = control;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonHabitante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEventos = new javax.swing.JButton();
        botonTarjeton = new javax.swing.JButton();
        botonAdministrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonHabitante.setText("HABITANTE");
        botonHabitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabitanteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unidad Habitacional v1.0");

        botonEventos.setText("Eventos");
        botonEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventosActionPerformed(evt);
            }
        });

        botonTarjeton.setText("Tarjeton");
        botonTarjeton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTarjetonActionPerformed(evt);
            }
        });

        botonAdministrar.setText("Administar");
        botonAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAdministrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTarjeton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonHabitante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(botonEventos)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonHabitante)
                    .addComponent(botonEventos))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTarjeton)
                    .addComponent(botonAdministrar))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHabitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabitanteActionPerformed
        dispose();
        control.controlHabitante();
    }//GEN-LAST:event_botonHabitanteActionPerformed

    private void botonEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventosActionPerformed
        dispose();
        control.controlEventos();
    }//GEN-LAST:event_botonEventosActionPerformed

    private void botonTarjetonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTarjetonActionPerformed
        dispose();
        control.controlTarjeton();
    }//GEN-LAST:event_botonTarjetonActionPerformed

    private void botonAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministrarActionPerformed
        // TODO add your handling code here:
        dispose();
        control.controlAdministrar();
    }//GEN-LAST:event_botonAdministrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrar;
    private javax.swing.JButton botonEventos;
    private javax.swing.JButton botonHabitante;
    private javax.swing.JButton botonTarjeton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
